[[plugins]]
repo = 'cespare/vim-toml'
on_ft = 'toml'

[[plugins]]
repo = 'davidhalter/jedi-vim'
on_ft = 'python'
hook_add = '''
if !exists('g:neocomplete#sources#omni#input_patterns')
	let g:neocomplete#sources#omni#input_patterns = {}
endif
let g:neocomplete#sources#omni#input_patterns.python = ''
let g:jedi#popup_select_first = 0
let g:jedi#popup_on_dot = 0
let g:jedi#goto_command = "<leader>d"
let g:jedi#goto_assignments_command = "<leader>g"
let g:jedi#goto_definitions_command = ""
let g:jedi#documentation_command = "K"
let g:jedi#usages_command = "<leader>n"
let g:jedi#rename_command = "<leader>R"

let g:jedi#force_py_version = 3

autocmd FileType python setlocal completeopt-=preview
'''

[[plugins]]
repo = 'lambdalisue/vim-pyenv'
on_ft = 'python'

[[plugins]]
repo = 'zchee/deoplete-jedi'
on_ft = 'python'
hook_add = '''
let g:python3_host_prog = $PYENV_ROOT . '/shims/python3'
'''

[[plugins]]
repo = 'tell-k/vim-autopep8'
on_ft = 'python'

[[plugins]]
repo = 'lervag/vimtex'
on_ft = 'tex'
hook_add = '''
let g:tex_flavor="latex"
'''

[[plugins]]
repo = 'KeitaNakamura/tex-conceal.vim'
on_ft = 'tex'
hook_add = '''
set conceallevel=2
let g:tex_conceal='adgmd'
set concealcursor=""
'''

[[plugins]]
repo = 'myhere/vim-nodejs-complete'
on_ft = 'javascript'
hook_add = '''
let g:nodejs_complete_config = {
\  'js_compl_fn': 'javascriptcomplete#CompleteJS',
\  'max_node_compl_len': 15
\}
'''

[[plugins]]
repo = 'mattn/emmet-vim'
on_ft = ['html', 'ejs']

